version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - '5431:5432'
    volumes:
      - db:/var/lib/postgresql/data
  app:
    container_name: "app"
    image: andre/app:latest
    ports:
      - "8081:8081"
volumes:
  db:
    driver: local
